### ISSUE TITLE
Running .rpc() results in missing API key

### ISSUE THREAD

**Issue by kay-es** [supabase/supabase-py#24]
# Bug report

## Describe the bug

Running the .rpc() method to call a stored procedure ends up with a response containing the following message:
**No API key found in request**

Using .table() with works fine.

## Additional context
I'm not sure if this is a bug or if i miss a place passing the required api key but according to the documentation and looking into the code, there is no place where i should pass a key additionally to the supabase_key

**Comment by kay-es** [comment]
Found the solution: To run a query via the httpx client successfully, we need to add an additional apikey header with the supabase key as value. You could fix that within the auth method in the PostgrestClient class.

Workaround manipulating the session headers:
```
supabase.postgrest.session.headers["apikey"] = supabase.postgrest.session.headers["Authorization"][7:]
result = await supabase.rpc('<PROCEDURE>', { "key": value})

```

**Comment by cacosandon** [comment]
thanks @kay-es ! I think we should re-open this issue. still happening on new versions.

**Comment by akarshghale** [comment]
> thanks @kay-es! I think we should re-open this issue. still happening on new versions.

Hi, yes this issue still happening.

**Comment by anand2312** [comment]
This is because the PostgREST server itself doesn't expect this header, but supabase does. As postgrest-py is supposed to work with any generic postgREST server (and not only with supabase) we do not set the apiKey header here. If you use the https://github.com/supabase-community/supabase-py library (that uses this library under the hood) it sets the header for you correctly.
