### ISSUE TITLE
Connection Keep Alive

### ISSUE THREAD

**Issue by StanGirard** [supabase/supabase-py#783]
Hey !

It seems that the TLS Handshake happens every query. 

<img width="717" alt="image" src="https://github.com/supabase-community/supabase-py/assets/19614572/1ebb1f74-4791-494e-98e9-9604135fd1bd">

Implementing a Keep-alive and keeping the connection alive would save around 60ms per query.

**Comment by juancarlospaco** [comment]
is it really required? 🤔 

- https://serverfault.com/a/790302
- https://g.co/gemini/share/5915292ee17d

Also, it should be ON by default whatsoever, because it is hardcoded:

- https://github.com/encode/httpx/blob/4b85e6c3898b94e686b427afd83138c87520b479/httpx/_client.py#L292
- https://github.com/encode/httpx/blob/4b85e6c3898b94e686b427afd83138c87520b479/CHANGELOG.md?plain=1#L1068
- https://github.com/encode/httpx/blob/4b85e6c3898b94e686b427afd83138c87520b479/tests/client/test_headers.py#L38

It is interesting nevertheless, I will keep investigating...

**Comment by StanGirard** [comment]
Hey @juancarlospaco,

I've been battling with it for almost a week. 

Going with direct connection to the database with RAW SQL queries makes it way faster. I looked into Kong, it should be around 8ms of latency not 40ms. 

There might be something funny happening. 

<img width="1353" alt="image" src="https://github.com/supabase-community/supabase-py/assets/19614572/e3607b05-bd70-4ea9-a023-0b66ca0c91bb">

Here you can see the time when I do queries directly to database and when using the python sdk. 

Would love to help you investigate. 

Both my backend and my supabase are in Ireland on AWS.

**Comment by StanGirard** [comment]
@juancarlospaco Thanks Juan! Let me know if i can help anyhow

**Comment by StanGirard** [comment]
Hello @juancarlospaco, any update of this issue ?

**Comment by juancarlospaco** [comment]
As explained at https://github.com/supabase/supabase-py/issues/783#issuecomment-2087544554
it is enabled and hardcoded from httpx, and basically nowadays it is mostly ignored whatsoever.

Make sure you are not running too old libs, or running in an env in debug mode 
(sometimes things are slower or different in debuggers to with debug mode active etc).

In the latest version of the clients, it has HTTP2 enabled which ignores all of this and uses persistent connections by default.

**Comment by silentworks** [comment]
Closing as there has been no reply from OP for over a month.
