### ISSUE TITLE
sign_in_with_password locking python unittest 

### ISSUE THREAD

**Issue by FelipeNFL** [supabase/supabase-py#844]
# Bug report

## Describe the bug

I'm using the Supabase Client Python with the unittest library to make some asserts in a data transform. But, if when I use the `sign_in_with_password()` method in the setUpClass to log in the project, the terminal is locked after the tests execution. The process is not kill and the Ctrl+C doesn't work too. I tried to call `close()` in the auth, but the problem persists. It appears there to be some deadlock.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Import the supabase in a unittest file
2. Create a client
3. Call `sign_in_with_passwod()` in the setUpClass
4. Wait for the test execution end
5. See the error

## Expected behavior

The process needs to be killed when the test finishes.

## System information

- OS: Windows 11
- Version of supabase-python: 2.5.1
- Version of Python: 3.12.3

**Comment by silentworks** [comment]
You just need to sign_out in order for it to not be locked. This has been discussed in a past issue. 

The discussion here with one solution of calling `sign_out`: https://github.com/supabase-community/supabase-py/issues/494#issuecomment-1778224450
Another solution here of passing a config property: https://github.com/supabase-community/supabase-py/issues/451#issuecomment-1736329894

**Comment by chriscarrollsmith** [comment]
Here's my use case: I'm trying to pass the user's JWT token from a Javascript frontend to a Python backend so that I can log the user in on the backend and perform RLS-protected operations. I'm using `supabase.auth.set_session` to get the job done. This causes Pytest to hang, and `supabase.auth.sign_out()` doesn't fix the issue in this case.

I mean, it might just be that this is a bad approach. I suspect that signout on the backend will sign the user out from the frontend too, although I've not even gotten that far in my testing due to this Pytest issue. So at the moment, I'm leaning toward dropping the whole idea of passing the session from frontend to backend like this.

But if there's a way to clean up the threads associated with `supabase.auth.set_session`, and to do it without signing out the user on the frontend, I'd love to know about it.

**Comment by silentworks** [comment]
Did you try the other solution of passing the config property on initiating the client in Python?

**Comment by chriscarrollsmith** [comment]
> @chriscarrollsmith Did you try the other solution of passing the config property on initiating the client in Python?
> 
> Also @chriscarrollsmith are you the same person as @FelipeNFL?

Thanks; I so.ehow missed that in your reply above and will give it a try. (No, I am not the same person as Felipe.)

**Comment by silentworks** [comment]
Closing out as no reply from OP for more than two months.
