### ISSUE TITLE
Cannot insert a Decimal

### ISSUE THREAD

**Issue by rdong8** [supabase/supabase-py#967]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Attempting to insert a `decimal.Decimal` results in this error:

```
TypeError: Object of type Decimal is not JSON serializable"
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```python
from decimal import Decimal

from supabase import create_async_client

async def main() -> None:
    client = await create_async_client(...)
    await (
        client
        .from_("test")
        .upsert({'percentage': Decimal(0.5)})
        .execute()
    )

asyncio.run(main())
```

## Expected behavior

The Decimal is inserted as is [done by `psycopg2`](https://www.psycopg.org/psycopg3/docs/basic/adapt.html#numbers-adaptation).

## System information

- OS: [e.g. macOS, Windows] Linux
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by webdrakib** [comment]
To address the bug you encountered while attempting to insert a Decimal value into Supabase, it’s essential to ensure that the value is correctly serialized to JSON before being sent. Since the Decimal type is not JSON serializable by default, you will need to convert it to a format that can be serialized, such as a float or a string.

Here’s a revised version of your code to handle this issue:

# Updated Code
`import asyncio
from decimal import Decimal
from supabase import create_async_client
async def main() -> None:
    client = await create_async_client(...)
    # Convert Decimal to float before inserting
    percentage_value = Decimal(0.5)
    await (
        client
        .from_("test")
        .upsert({'percentage': float(percentage_value)})  # Convert Decimal to float
        .execute()
    )
asyncio.run(main())`

## Explanation of Changes

1. **Convert Decimal to Float:** The Decimal value is converted to a float using float(percentage_value). This ensures that the value can be serialized to JSON without causing a TypeError.
2. **Maintaining Precision:** If you need to maintain precision and avoid floating-point arithmetic issues, consider converting the Decimal to a string instead:
`await (
    client
    .from_("test")
    .upsert({'percentage': str(percentage_value)})  # Convert Decimal to string
    .execute()`

**Comment by silentworks** [comment]
Yes converting the decimal to a string or float is the way. The library won't convert every Python type for you so you have to handle that yourself. `psycopg` supports that because its probably doing some conversion internally for you.
